language: python
python:
  - "3.7"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv Home-assistant-google-home-travis.yaml Home-assistant-google-home.yaml
  - sudo apt-get install -y libudev-dev
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config