
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include themes.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
mobile_app:

discovery:
  # ignore:
  #   - igd
    
# https://www.home-assistant.io/integrations/recorder/
recorder:
  # purge_interval: 2
  purge_keep_days: 30
  db_url: !secret db_url
  exclude:
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.sonarr_wanted
media_dirs:
  local: /media
  radio: /radio

light: !include lights.yaml

zone: !include zones.yaml

switch: !include switches.yaml

# https://github.com/StyraHem/ShellyForHASS/issues/72
shelly:
  discovery: true  #add all devices (default)
  sensors: #sensors to show, can be override on each device
    - all
  devices:  #configure devices
    - id: "D0E58B"
      light_switch: true  #add this switch as a light
      name: "Gangur shelly"
    - id: "98f4abf283d7"
      name: "Vifta"
  #     sensors: [ switch ] #Override the global sensor
  #   - id: "7BD5F3"

cloud:
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations
# automation: !include automations.yaml
script: !include_dir_merge_named scripts
# script: !include scripts.yaml

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages
python_script:
shopping_list:
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - host: 192.168.1.7
      key: !secret aquara_key

sensor: !include sensors.yaml

# media_player:
  # - platform: spotify
  #   client_id: !secret spotify_client_id
  #   client_secret: !secret spotify_client_secret
    # aliases:
    #     abc123def456: 'Living Room'
    #     9183abas000: 'Bed Room'

notify:
  - name: pushbullet_notify
    platform: pushbullet
    api_key: !secret pushbullet_token
  - name: all_phones
    platform: group
    services:
    - service: mobile_app_jens_mobile
    - service: mobile_app_pixel_2_xl

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    delay_time: 0
    arming_time: 0
    disarmed:
      trigger_time: 0
    # armed_night:
    #   pending_time: 0
    #   delay_time: 0
    armed_away:
      arming_time: 60
      delay_time: 60


ombi:
  host: !secret ombi_host
  username: !secret ombi_username
  api_key: !secret ombi_api_key
  port: 3579
  # ssl: true

# https://www.home-assistant.io/integrations/speedtestdotnet
speedtestdotnet:
  scan_interval:
    minutes: 60
  server_id: 6471
  monitored_conditions:
    - ping
    - download
    - upload

binary_sensor:
#   - platform: ping
#     host: 10.0.0.17
#     name: 'Hertz'
#   - platform: ping
#     host: 10.0.0.7
#     name: 'Xiaomi Gateway'
#   - platform: ping
#     host: 10.0.0.10
#     name: 'Wifi Extender'
#   - platform: ping
#     host: !secret hue_hub_ip
#     name: 'Hue Gateway'
#   - platform: ping
#     host: 10.0.0.12
#     name: 'Bytes'
#   - platform: ping
#     host: 10.0.0.8
#     name: 'Ioniq'

    #Hass Groups
  - platform: template
    sensors:
      garage_motion:
        friendly_name: "Bílskúr hreyfing"
        # entity_id:
        #   - group.garage_motion
        device_class: motion
        value_template: "{{ is_state('group.garage_motion', 'on')}}"
      hallway_motion:
        friendly_name: "Gangur hreyfing"
        # entity_id:
        #   - group.hallway_motion
        device_class: motion
        value_template: "{{ is_state('group.hallway_motion', 'on')}}"
  # - platform: mqtt
    # name: Shelly Gangur
    # state_topic: “shellies/shellydimmer-D0E58B/relay/0”
    # qos: 0
    # payload_on: “on”
    # payload_off: “off”

  # - platform: mqtt
  #   schema: template
  #   name:  Shelly Dimmer
  #   state_topic: "shellies/shellydimmer-XXXXXX/light/0/status"
  #   state_template: '{% if value_json.ison %} on {% else %} off {% endif %}'
  #   command_topic: "shellies/shellydimmer-XXXXXX/light/0/set"
  #   command_on_template: '{"turn": "on"{% if brightness is defined %}, "brightness": {{(brightness | float * 0.3882 + 1) | round(0)}}{% endif %}}'
  #   command_off_template: '{"turn": "off"}'
  #   brightness_template: '{{ (value_json.brightness | float * 2.55) | round(0) }}'
    # retain: true
    # optimistic: false
    
# shell_command:
#   update: /config/shell_scripts/gitpull.sh

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

google_assistant:
  project_id: !secret google_home_project_id
  service_account: !include Home-assistant-google-home.json
  report_state: true
  exposed_domains:
    - switch
    - light
  # entity_config:
  #   switch.kitchen:
  #     name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
  #     aliases:
  #       - BRIGHT_LIGHTS
  #       - ENTRY_LIGHTS
  #   light.living_room:
  #     expose: false
  #     room: LIVING_ROOM


mqtt:
  discovery: true
  broker: !secret mqtt_ip
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

webhook:

# zigbee2mqtt_networkmap:
#   #topic: your topic (optional, default zigbee2mqtt)
# panel_iframe:
#   networkmap:
#     title: 'Zigbee Map'
#     url: '/local/community/zigbee2mqtt_networkmap/map.html'
#     icon: 'mdi:graphql'

input_boolean: !include input_booleans.yaml
