- platform: flux
  lights:
    - light.forstofa
    - light.bilskur
    - light.gangur
    - light.stigi
    - light.stofa
    - light.eldhus
    - light.eyja
    - light.matarbord
    - light.hjonaherbergi_gangur
  name: Fluxer
  start_time: '7:00'
  stop_time: '23:00'
  start_colortemp: 3500
  sunset_colortemp: 2700
  stop_colortemp: 1900
  brightness: 185
  disable_brightness_adjust: true
  mode: mired
  transition: 30
  interval: 120

- platform: mqtt
  schema: template
  name:  Shelly Dimmer
  state_topic: "shellies/shellydimmer-D0E58B/light/0/status"
  state_template: '{% if value_json.ison %} on {% else %} off {% endif %}'
  command_topic: "shellies/shellydimmer-D0E58B/light/0/set"
  command_on_template: '{"turn": "on"{% if brightness is defined %}, "brightness": {{(brightness | float * 0.3882 + 1) | round(0)}}{% endif %}}'
  command_off_template: '{"turn": "off"}'
  brightness_template: '{{ (value_json.brightness | float * 2.55) | round(0) }}'