- alias: Turn on bathroom lights downstairs
  trigger:
    platform: state
    entity_id: sensor.bathroom_downstairs_motion_occupancy
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.bathroom_downstairs_light

- alias: Turn off bathroom lights downstairs
  trigger:
    platform: state
    entity_id: sensor.bathroom_downstairs_motion_occupancy
    to: 'off'
    for:
      minutes: 2
  action:
    service: light.turn_off
    entity_id: light.bathroom_downstairs_light