- alias: "Baðherbergi niðri kveikja"
  description: "Kveikja á ljósum sjálfkrafa á gangi"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bathroom_downstairs_motion_occupancy
      to: "on"
  action:
      service: light.turn_on
      entity_id: light.bathroom_downstairs_light

- alias: "Baðherbergi niðri slökkva"
  description: "Slökkva á ljósum sjálfkrafa á gangi" 
  condition: #Ekki slökkva á næturnar
    condition: not
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: 'armed_night'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bathroom_downstairs_motion_occupancy
      to: "off"
      for:
        minutes: 5
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom_downstairs_light
