- alias: "Gangur kveikja ljós"
  description: "Kveikja á ljósum sjálfkrafa á gangi"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hallway_motion
      to: "on"
  action:
      service: light.turn_on
      entity_id: light.gangur
      data_template:
        brightness_pct: >-
          {%- set hour = now().hour | int -%}
          {%- if   hour >  19 and hour <  8                  -%}10
          {%- else                                           -%}70  
          {%- endif -%}

- alias: "Gangur slökkva ljós"
  description: "Slökkva á ljósum sjálfkrafa á gangi"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hallway_motion
      to: "off"
      for:
        minutes: 5
  action:
    service: light.turn_off
    data:
      entity_id: light.gangur
      transition: 3
