- alias: "Office ljós brightnes -"
  description: "Skrifstofa ljós brightness down"
  trigger:
    - platform: state
      entity_id:
        - sensor.wireless_double_button_click
      to: "left"
  action:
      service: light.turn_on
      entity_id: light.garage_ofiice
      data:
        brightness_step_pct: -10


- alias: "Office ljós brightnes +"
  description: "Skrifstofa ljós brightness up"
  trigger:
    - platform: state
      entity_id:
        - sensor.wireless_double_button_click
      to: "right"
  action:
      service: light.turn_on
      entity_id: light.garage_ofiice
      data:
        brightness_step_pct: 10


- alias: "Office ljós toggle"
  description: "Skrifstofa ljós toggle"
  trigger:
    - platform: state
      entity_id:
        - sensor.wireless_double_button_click
      to: "both"
  action:
      service: light.toggle
      entity_id: light.garage_ofiice
