#Alarm is triggered sequence
- alias: 'Alarm is triggered'
  # hide_entity: true
  initial_state: true
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'triggered'
  action:
  - service: script.turn_on
    data:
      entity_id: script.start_alarm
  #kveikja á xiami alert

- alias: 'Alarm is deactivated'
  # hide_entity: true
  initial_state: true
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from: 'triggered'
      to: 'disarmed'
  action:
  - service: script.turn_on
    data:
      entity_id: script.stop_alarm
  # - service: notify.pushbullet_notify
  #   data_template:
  #     title: Þjófavörn tekin af!
  #     message: 'Þjófavörn tekin af, eftir að hafa farið í gang.'
  - service: notify.all_phones
    data:
      message: clear_notification
      data:
        tag: alarm_on


#Armed away trigger not vacuming
- alias: 'Armed away trigger not vacuming'
  # hide_entity: true
  initial_state: true
  trigger:
  - entity_id: 
      - binary_sensor.motion_sensor_hallway_1st
      - binary_sensor.door_window_sensor_forstofa
      - binary_sensor.door_window_sensor_laundry
      - binary_sensor.door_sensor_svalahurd_nidri
      - binary_sensor.office_motion_sensor_occupancy
      # # - binary_sensor.forstofa_motion_sensor_occupancy  #posturinn fer stundum í það
      #- binary_sensor.garage_motion_sensor_workstation_occupancy
      #- binary_sensor.motion_sensor_garage
      - binary_sensor.motion_sensor_hallway_second
      - binary_sensor.door_window_sensor_kitchen
      - binary_sensor.living_room_door_contact
      - binary_sensor.motion_hallway_2_occupancy
    platform: state
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
    - condition: not
      conditions:
      - condition: state
        entity_id: vacuum.alfred
        state: 
          - "cleaning"
          - "returning"
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm

#Armed away trigger while vacuming
- alias: 'Armed away trigger while vacuming'
  # hide_entity: true
  initial_state: true
  trigger:
  - entity_id: 
      - binary_sensor.door_window_sensor_forstofa
      - binary_sensor.door_window_sensor_laundry
      - binary_sensor.door_sensor_svalahurd_nidri
      - binary_sensor.door_window_sensor_kitchen
      - binary_sensor.living_room_door_contact
    platform: state
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
    - condition: state
      entity_id: vacuum.alfred
      state: 
        - "cleaning"
        - "returning"
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm


#Someone comes home, wait time before trigger
# - alias: 'armed_away_before_trigger'
#   trigger:
#   - entity_id: alarm_control_panel.alarm_trigger
#     platform: state
#     from: 'armed_away'
#     to: 'pending'
#   action:
#     service: light.turn_on
#     entity_id: light.gateway_light

#Armed night trigger
- alias: 'Armed night trigger'
  # hide_entity: true
  initial_state: true
  trigger:
  - entity_id: 
    # - binary_sensor.motion_sensor_hallway_1st
    - binary_sensor.door_window_sensor_forstofa
    - binary_sensor.door_window_sensor_laundry
    - binary_sensor.door_sensor_svalahurd_nidri
    - binary_sensor.door_window_sensor_kitchen
    #- binary_sensor.motion_sensor_garage
    #- binary_sensor.garage_motion_sensor_workstation_occupancy
    - binary_sensor.office_motion_sensor_occupancy
    - binary_sensor.living_room_door_contact
    # - binary_sensor.forstofa_motion_sensor_occupancy
    platform: state
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_night
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm

- alias: 'Slökkva 06:00'
  initial_state: true
  description: ''
  trigger:
    platform: time
    at: "06:00:00"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_night
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm

- alias: 'Slökkva þegar Armed night'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_night'
  action:
    - service: light.turn_off
      data:
        entity_id: 
        - light.stairs
        - light.stofa
        - light.eldhus
        - light.matarbord
        - light.stairs_master_bedroom
        - light.bilskur
        - light.geymsla
        - light.forstofa
        - light.laundry_light
        - light.hue_white_lamp_1
        # transition: 5
    - service: light.turn_on
      data:
        entity_id: 
        - light.gangur
        transition: 5
        brightness: 20


- alias: 'Slökkva á öllu þegar Armed away'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_away'
  action:
    - service: notify.mobile_app_jens_mobile
      data_template:
        title: Armed away
        message: 'Þjófavörn sett a armed away'
    - service: homeassistant.turn_off
      entity_id:
        - group.downstairs_lights
        - group.upstairs_lights
        - group.upstairs_devices
    - service: homeassistant.turn_on
      entity_id:
        - automation.turn_on_lights_upstairs
        - automation.turn_on_lights_downstairs
