- alias: 'Notify if doors open when armed'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_night'
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_away'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_kitchen
        state: 'on'
      - condition: state
        entity_id: binary_sensor.door_window_sensor_laundry
        state: 'on'
      - condition: state
        entity_id: binary_sensor.door_sensor_svalahurd_nidri
        state: 'on'
      - condition: state
        entity_id: binary_sensor.door_window_sensor_forstofa
        state: 'on'
  action:
    - service: notify.mobile_app_jens_mobile
      data_template:
        title: "{{ 'Hurð opin !!'"
        message: >-
          {% for state in states.sensor %}
            {{ state.entity_id }} = {{ state.state }},
          {% endfor %}
      # data_template:
      #   title: Hurð opin!
      #   message: 'Það er hurð opin'