- alias: 'Notify if doors open when armed'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_night'
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_away'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.all_doors
        state: 'on'
  action:
    - service: notify.mobile_app_jens_mobile
      data_template:
        title: "Hurð opin !!"
        message: >-
          {% for state in states.group.all_doors %}
            {% if {{state.state}} is 'on') %}
              {{ state.name }} er opin!
            {% endif %}
          {% endfor %}
      # data_template:
      #   title: Hurð opin!
      #   message: 'Það er hurð opin'