- alias: Kveikja á ljósum í forstofu
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.forstofa_motion_sensor_occupancy
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_forstofa
      to: 'on'
  action:
    service: light.turn_on
    entity_id: light.forstofa

- alias: Slökkva á ljósum forstofu
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.forstofa_motion_sensor_occupancy
      to: 'off'
      for:
        minutes: 1
    - platform: state
      entity_id: binary_sensor.door_window_sensor_forstofa
      to: 'off'
      for:
        minutes: 1
  condition:
    condition: or
    conditions:
        - condition: state
          entity_id: binary_sensor.forstofa_motion_sensor_occupancy
          state: 'off'
        - condition: state
          entity_id: binary_sensor.door_window_sensor_forstofa
          state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.forstofa
      transition: 3