# Turn on red light in office when front door open
- alias: "Rautt ljós þegar útidyrahurð opin"
  trigger:
  - entity_id: binary_sensor.door_window_sensor_forstofa, binary_sensor.door_window_sensor_laundry, binary_sensor.door_sensor_svalahurd_nidri
    platform: state
    to: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.gateway_light
        color_name: red

# Turn off red light in office when front door closes
- alias: "Slökkva Rautt ljós þegar útidyrahurð lokast"
  trigger:
  - entity_id: binary_sensor.door_window_sensor_forstofa, binary_sensor.door_window_sensor_laundry, binary_sensor.door_sensor_svalahurd_nidri
    platform: state
    to: 'off'
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.gateway_light