- alias: Turn on garage lights of there is movement
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.garage_motion
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.bilskur, light.geymsla

- alias: Turn off corridor light x minutes after last movement
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.garage_motion
    to: 'off'
    for:
      minutes: 2
  action:
    service: light.turn_off
    entity_id: light.bilskur, light.geymsla