- alias: Turn on garage lights of there is movement
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.garage_motion
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.bilskur

- alias: Turn off garage lights of there is no movement
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.garage_motion
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    data:
      entity_id: light.bilskur
      # transition: 3