# Turn on first morning motion automations
- alias: 'Kveikja ljós við hreyfingu á morgnana'
  initial_state: true
  trigger:
    - at: 06:30:00
      platform: time
  action:
    service: 'homeassistant.turn_on'
    entity_id: automation.turn_on_lights_downstairs, automation.turn_on_lights_upstairs
