- alias: 'Kveikja ef hreyfing um nótt'
  # hide_entity: false
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_hallway_second
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_night'
  action:
    - service: light.turn_on
      data:
        entity_id: 
          - light.eyja
          - light.glass_cabinets
          - light.badherbergi
        brightness: 50
        kelvin: 2200
        transition: 3

- alias: 'Slökkva ef engin hreyfing um nótt'
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_hallway_second
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_night'
  action:
    - service_template: 'light.turn_off'
      data:
        entity_id: 
          - light.eyja
          - light.glass_cabinets
          - light.badherbergi
        transition: 5

# # Downstairs
# - alias: 'Kveikja niðri - nótt'
#   # hide_entity: false
#   trigger:
#     - platform: state
#       entity_id: 
#         - binary_sensor.motion_hallway_2_occupancy
#         - binary_sensor.motion_sensor_hallway_1st
#       to: 'on'
#   condition:
#     - condition: state
#       entity_id: alarm_control_panel.home_alarm
#       state: 'armed_night'
#   action:
#     - service: light.turn_on
#       data:
#         entity_id: 
#           - light.gangur
#         brightness: 50
#         kelvin: 2200
#         transition: 3

  
# - alias: 'Slökkva niðri - nótt'
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: 
#         - binary_sensor.motion_hallway_2_occupancy
#         - binary_sensor.motion_sensor_hallway_1st
#       to: 'off'
#       for:
#         minutes: 2
#   condition:
#     condition: and
#     conditions:
#       - condition: state
#         entity_id: alarm_control_panel.home_alarm
#         state: 'armed_night'
#       - condition: state
#         entity_id: binary_sensor.motion_hallway_2_occupancy
#         state: 'off'  
#       - condition: state
#         entity_id: binary_sensor.motion_sensor_hallway_1st
#         state: 'off'  
#   action:
#     - service_template: 'light.turn_off'
#       data:
#         entity_id: 
#           - light.gangur
#         transition: 10
      

# Stairs
# - alias: 'Kveikja í stiga ef hreyfing um nótt'
#   hide_entity: false
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_hallway_second, binary_sensor.motion_sensor_hallway_1st
#       to: 'on'
#   condition:
#     # condition: or
#     # conditions:
#     # - condition: state
#     #   entity_id: alarm_control_panel.home_alarm
#     #   state: 'triggered'
#     # - condition: time
#     #   after: '00:00:00'
#     #   before: '06:30:00'
#     - condition: time
#       after: '00:00:00'
#       before: '06:30:00'
#   action:
#     - service: light.turn_on
#       data:
#         entity_id: light.stairs_l1, light.stairs_r1, light.stairs_l2, light.stairs_r2, light,stairs_l3, light,stairs_r3
#         brightness: 50
#         kelvin: 2200
#         transition: 3

# - alias: 'Slökkva í stiga ef engin hreyfing um nótt'
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_hallway_second, binary_sensor.motion_sensor_hallway_1st
#       to: 'off'
#       for:
#         minutes: 1
#   condition:
#     # - condition: or
#     #   conditions:
#     #   - condition: state
#     #     entity_id: alarm_control_panel.home_alarm
#     #     state: 'triggered'
#       # - condition: time
#       #   after: '00:00:00'
#       #   before: '06:30:00'
#     - condition: time
#       after: '00:00:00'
#       before: '06:30:00'
#     - condition: and
#       conditions:
#         - condition: state
#           entity_id: 'binary_sensor.motion_sensor_hallway_second'
#           state: 'off'
#         - condition: state
#           entity_id: 'binary_sensor.motion_sensor_hallway_1st'
#           state: 'off'
#   action:
#     - service_template: 'light.turn_off'
#       data_template:
#         entity_id: light.stairs_l1, light.stairs_r1, light.stairs_l2, light.stairs_r2, light,stairs_l3, light,stairs_r3
#         # transition: 10


# Kitchen
# Add second sensor in kitchen?
# - alias: 'turn_on_night_lights_kitchen'
#   hide_entity: false
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_hallway_1st
#       to: 'on'
#   condition:
#   - condition: time
#     after: '12:00:00'
#     before: '06:30:00'
#   action:
#     - service: light.turn_on
#       data:
#         entity_id: light.eldhus
#         brightness: 10
#         kelvin: 2200
#     -  service: light.turn_on
#           data:
#             entity_id: light.eldhus
#             brightness: 10
#             kelvin: 2200

# Kitchen
# glerskapar
# Bathroom
# downstairs
# forstofa
