# Stairs

- alias: 'Kveikja á ljósum í stiga ef hreyfing um nótt'
  hide_entity: false
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_hallway_second ,binary_sensor.motion_sensor_hallway_1st
      to: 'on'
  # condition:
  # - condition: time
  #   after: '12:00:00'
  #   before: '06:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.stairs_l1, light.stairs_r1, light.stairs_l2, light.stairs_r2
        brightness: 50
        kelvin: 2200
        transition: 3

- alias: 'Slökkva á ljósum í stiga ef hreyfing um nótt'
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_hallway_second ,binary_sensor.motion_sensor_hallway_1st
      to: 'off'
      for:
        minutes: 1
  condition:
    # - condition: time
    #   after: '00:00:00'
    #   before: '06:30:00'
    - condition: and
      conditions:
        - condition: state
          entity_id: 'binary_sensor.motion_sensor_hallway_second'
          state: 'off'
        - condition: state
          entity_id: 'binary_sensor.motion_sensor_hallway_1st'
          state: 'off'
  action:
    - service_template: 'light.turn_off'
      data_template:
        entity_id: light.stairs_l1, light.stairs_r1, light.stairs_l2, light.stairs_r2
        transition: 10


# Kitchen
# Add second sensor in kitchen?
# - alias: 'turn_on_night_lights_kitchen'
#   hide_entity: false
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_hallway_1st
#       to: 'on'
#   condition:
#   - condition: time
#     after: '12:00:00'
#     before: '06:30:00'
#   action:
#     - service: light.turn_on
#       data:
#         entity_id: light.eldhus
#         brightness: 10
#         kelvin: 2200
#     -  service: light.turn_on
#           data:
#             entity_id: light.eldhus
#             brightness: 10
#             kelvin: 2200

# Kitchen
# glerskapar
# Bathroom
# downstairs
# forstofa
