
- alias: 'turn_on_lights_downstairs'
  initial_state: false
  # hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_hallway_1st
      to: 'on'
  action:
    - service: 'light.turn_on'
      data_template:
        entity_id: 
          - light.stairs
          - light.bathroom_downstairs_light
          - light.laundry_light
        brightness: 185
    - service: 'homeassistant.turn_off'
      data_template:
        entity_id: automation.turn_on_lights_downstairs


- alias: 'turn_on_lights_upstairs'
  initial_state: false
  # hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_hallway_second
      to: 'on'
  action:
    - service: 'light.turn_on'
      data_template:
        entity_id: 
          - light.eldhus
          - light.stofa
          - light.matarbord
          - light.eyja
          - light.badherbergi
          - light.olga_lampi
          # - light.master_bedroom
          # - light.stairs_master_bedroom
          # - light.fataskapur
        # transition: 120
        transition: 3
        brightness: 185
    - service: 'homeassistant.turn_off'
      data_template:
        entity_id: automation.turn_on_lights_upstairs