
- alias: 'turn_on_lights_downstairs'
  initial_state: false
  # hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_hallway_1st
      to: 'on'
  action:
    - service_template: 'light.turn_on'
      data_template:
        entity_id: 
          - light.stigi
          - light.bathroom_downstairs_light
          - light.laundry_light
    - service_template: 'homeassistant.turn_off'
      data_template:
        entity_id: automation.turn_on_lights_downstairs


- alias: 'turn_on_lights_upstairs'
  initial_state: false
  # hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_hallway_second
      to: 'on'
  action:
    - service_template: 'light.turn_on'
      data_template:
        entity_id: 
          - light.eldhus
          - light.glass_cabinets
          - light.stofa
          - light.matarbord
          - light.eyja
          - light.badherbergi
          - light.master_bedroom1
          - light.stairs_master_bedroom_light
          - light.fataskapur_light
    - service_template: 'homeassistant.turn_off'
      data_template:
        entity_id: automation.turn_on_lights_upstairs