- alias: "Gangur shelly automation"
  trigger:
  - entity_id: binary_sensor.shelly_shdm_1_d0e58b_1_switch
    platform: state
    to: 'on'
  action:
    - service: notify.mobile_app_jens_mobile
      data_template:
        title: Switch i gang 'on'
    - service: light.toggle
      entity_id: light.gangur


# - alias: "Gangur off"
#   trigger:
#   - entity_id: light.shelly_shdm_1_d0e58b
#     platform: state
#     from: 'on'
#     to: 'odd'
#   action:
#     - service: light.turn_off
#       entity_id: light.gangur